const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),W=960,H=540,$=id=>document.getElementById(id);
const path=[[-30,110],[170,110],[170,300],[410,300],[410,150],[670,150],[670,390],[1010,390]];
let towers=[{x:88,y:390,level:1,evo:'base',cool:0}],crates=[],enemies=[],hits=[],coins=80,lives=12,score=0,wave=1,kills=0,spawned=0,running=false,spawnTimer=0,crateTimer=7,drag=null,last=0;
const evo={base:{name:'橡果守卫',icon:'🌰',color:'#8a633c',damage:16,range:115,rate:.72},thorns:{name:'荆棘之心',icon:'🌵',color:'#55a95d',damage:27,range:130,rate:.65},frost:{name:'霜叶守卫',icon:'❄️',color:'#69bdd0',damage:13,range:145,rate:.42},gold:{name:'黄金果核',icon:'✨',color:'#e6a831',damage:43,range:120,rate:.86}};
function ui(){ $('coins').textContent=coins;$('lives').textContent=lives;$('score').textContent=score;$('wave').textContent=wave;$('progressText').textContent=`${kills} / ${8+wave*3}`;$('progressBar').style.width=`${Math.min(100,kills/(8+wave*3)*100)}%`;document.querySelector('#towerList').innerHTML=`<div class="tower-card active"><div class="tower-art" style="background:${evo.base.color}33">🌰</div><div><b>橡果守卫</b><small>范围近战 · 可移动合成</small></div><span class="price">初始</span></div>`}
function pointAt(dist){let left=dist;for(let i=1;i<path.length;i++){let a=path[i-1],b=path[i],d=Math.hypot(b[0]-a[0],b[1]-a[1]);if(left<=d)return{x:a[0]+(b[0]-a[0])*left/d,y:a[1]+(b[1]-a[1])*left/d};left-=d}return{x:1010,y:390}}
function addEnemy(){let hp=34+wave*18+spawned*2;enemies.push({dist:0,x:-30,y:110,hp,max:hp,speed:34+wave*5,kind:wave%2?'🟢':'🟣',slow:0})}
function addCrate(){let x=70+Math.random()*800,y=55+Math.random()*420;if(path.some((p,i)=>i&&Math.hypot(x-p[0],y-p[1])<55))return;crates.push({x,y,hp:45+wave*15,max:45+wave*15})}
function burst(x,y,color){for(let i=0;i<7;i++)hits.push({x,y,life:1,color,vx:(Math.random()-.5)*55,vy:(Math.random()-.5)*55})}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#b6dda5';ctx.fillRect(0,0,W,H);for(let x=20;x<W;x+=42)for(let y=22;y<H;y+=42){ctx.fillStyle=(x+y)%84?'#b9dfa8':'#afd69d';ctx.beginPath();ctx.arc(x,y,1.5,0,7);ctx.fill()}ctx.lineWidth=52;ctx.lineCap='round';ctx.strokeStyle='#d8c58d';ctx.beginPath();path.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();ctx.lineWidth=43;ctx.strokeStyle='#f0dfad';ctx.beginPath();path.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();crates.forEach(c=>{ctx.fillStyle='#a66b35';ctx.fillRect(c.x-17,c.y-17,34,34);ctx.strokeStyle='#f2c36a';ctx.lineWidth=3;ctx.strokeRect(c.x-13,c.y-13,26,26);ctx.font='18px serif';ctx.textAlign='center';ctx.fillText('🎁',c.x,c.y+6);ctx.fillStyle='#fff';ctx.fillRect(c.x-18,c.y-25,36,4);ctx.fillStyle='#d67d3b';ctx.fillRect(c.x-18,c.y-25,36*Math.max(0,c.hp/c.max),4)});towers.forEach(t=>{let z=evo[t.evo];ctx.fillStyle='rgba(49,89,44,.18)';ctx.beginPath();ctx.arc(t.x,t.y,27,0,7);ctx.fill();ctx.fillStyle=z.color;ctx.beginPath();ctx.arc(t.x,t.y,20,0,7);ctx.fill();ctx.font='24px serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(z.icon,t.x,t.y);ctx.fillStyle='#fff';ctx.font='bold 11px Nunito';ctx.fillText('Lv '+t.level,t.x,t.y+31)});enemies.forEach(e=>{ctx.fillStyle=e.slow>0?'#78c6d4':'#d96d62';ctx.beginPath();ctx.arc(e.x,e.y,15,0,7);ctx.fill();ctx.font='17px serif';ctx.fillText(e.kind,e.x,e.y+1);ctx.fillStyle='#fff';ctx.fillRect(e.x-15,e.y-24,30,4);ctx.fillStyle='#65aa4f';ctx.fillRect(e.x-15,e.y-24,30*Math.max(0,e.hp/e.max),4)});hits.forEach(p=>{ctx.globalAlpha=p.life;ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,4,4);ctx.globalAlpha=1})}
function update(dt){if(running){spawnTimer-=dt;crateTimer-=dt;if(spawned<8+wave*3&&spawnTimer<=0){addEnemy();spawned++;spawnTimer=.7/Math.min(2,wave*.25+1)}if(crateTimer<=0){addCrate();crateTimer=8+Math.random()*5}if(spawned>=8+wave*3&&enemies.length===0){running=false;$('waveBtn').disabled=false;$('waveBtn').textContent=wave<5?`开始第 ${wave+1} 波 ▶`:'全部波次完成';if(wave<5)wave++;ui()}}enemies.forEach(e=>{if(e.slow>0)e.slow-=dt;e.dist+=e.speed*(e.slow>0?.4:1)*dt;Object.assign(e,pointAt(e.dist));if(e.dist>1030){e.dead=true;lives--;ui()}});towers.forEach(t=>{let z=evo[t.evo];t.cool-=dt;if(t.cool<=0){let target=enemies.find(e=>Math.hypot(e.x-t.x,e.y-t.y)<z.range);if(!target)target=crates.find(c=>Math.hypot(c.x-t.x,c.y-t.y)<z.range);if(target){target.hp-=z.damage*t.level;if(t.evo==='frost')target.slow=1.4;t.cool=z.rate;burst(target.x,target.y,z.color);if(target.hp<=0&&!target.dead){target.dead=true;if('dist'in target){coins+=10+wave;score+=100*t.level;kills++}else{towers.push({x:target.x,y:target.y,level:1,evo:'base',cool:0});$('message').textContent='宝箱破碎，新的橡果守卫加入了！'}}ui()}}});crates=crates.filter(c=>!c.dead);enemies=enemies.filter(e=>!e.dead&&e.hp>0);hits.forEach(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt});hits=hits.filter(p=>p.life>0);if(lives<=0){running=false;$('message').textContent='森林需要你的帮助，再试一次吧！';$('waveBtn').disabled=false;$('waveBtn').textContent='重新开始'}}
function loop(ts){let dt=Math.min(.05,(ts-last)/1000||0);last=ts;update(dt);draw();requestAnimationFrame(loop)}
function pos(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
canvas.addEventListener('pointerdown',e=>{let p=pos(e);drag=towers.find(t=>Math.hypot(t.x-p.x,t.y-p.y)<28);if(drag)canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(drag){let p=pos(e);drag.x=p.x;drag.y=p.y}});canvas.addEventListener('pointerup',()=>{if(!drag)return;let other=towers.find(t=>t!==drag&&Math.hypot(t.x-drag.x,t.y-drag.y)<35);if(other&&other.level===drag.level){other.level++;towers=towers.filter(t=>t!==drag);if(other.level%5===0){other.evoChanged=false;$('evoBox').classList.add('open');$('message').textContent='达到 5 的倍数等级，请选择进化方向！'}else $('message').textContent=`合成成功！橡果守卫 Lv.${other.level}`;}drag=null;ui()});
document.querySelectorAll('[data-evo]').forEach(b=>b.onclick=()=>{let t=towers.find(t=>t.level%5===0&&!t.evoChanged);if(t){t.evo=b.dataset.evo;t.evoChanged=true;$('evoBox').classList.remove('open');$('message').textContent=`进化完成：${evo[t.evo].name}`;ui()}});
$('waveBtn').onclick=()=>{if(lives<=0){lives=12;coins=80;score=0;wave=1;towers=[{x:88,y:390,level:1,evo:'base',cool:0}];enemies=[];crates=[];kills=0}spawned=0;kills=0;running=true;spawnTimer=0;crateTimer=5;$('waveBtn').disabled=true;$('waveBtn').textContent='波次进行中…';$('message').textContent='怪物来了！拖动橡果守卫保护宝箱。';ui()};$('soundBtn').onclick=()=>{$('soundBtn').textContent=$('soundBtn').textContent==='🔊'?'🔇':'🔊'};ui();requestAnimationFrame(loop);
