const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.GAME_URL || 'http://127.0.0.1:4175';
const output = process.env.SCREENSHOT_DIR || '/tmp/tafang-verification';

(async()=>{
  await fs.mkdir(output,{recursive:true});
  const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});
  try {
    for (const [width,height] of [[1440,1000],[768,1024],[390,844]]) {
      const page=await browser.newPage({viewport:{width,height},hasTouch:width<=768,isMobile:width===390}), errors=[],failed=[];
      page.on('pageerror',error=>errors.push(error.message));
      page.on('response',response=>{if(response.status()>=400)failed.push(response.url());});
      await page.route('**/*',route=>new URL(route.request().url()).origin===new URL(base).origin?route.continue():route.abort());
      await page.goto(base);await page.evaluate(()=>document.fonts.ready);
      // The command hub is the stable entry point. Exercise endless mode
      // before entering the finite campaign flow so both navigation paths are
      // covered by the browser smoke test.
      assert.equal(await page.locator('#hubPage').isVisible(),true);
      assert.equal(await page.locator('#campaignPage').isVisible(),false);
      await page.locator('#hubEndlessBtn').click();
      assert.equal(await page.locator('#battlePage').isVisible(),true);
      assert.equal(await page.evaluate(()=>gameSession.mode.kind),'endless');
      assert.equal(await page.locator('#waveTotal').textContent(),'/ ∞');
      assert.match(await page.locator('#waveBtn').textContent(),/开始冒险/);
      await page.locator('#battleBackBtn').click();
      assert.equal(await page.locator('#hubPage').isVisible(),true);
      await page.locator('.workshop-entry summary').click();
      assert.equal(await page.locator('#hubDeveloperBtn').isVisible(),true);
      await page.locator('#hubDeveloperBtn').click();
      assert.equal(await page.locator('#battlePage').isVisible(),true);
      assert.equal(await page.evaluate(()=>gameSession.mode.kind),'developer');
      assert.equal(await page.locator('#devTools').isVisible(),true);
      await page.locator('[data-dev-action="spirit"]').click();
      assert.ok(await page.evaluate(()=>Object.values(reserve).some(count=>count>0) || germinationOffers.some(offer=>!offer.claimed)));
      await page.locator('#battleBackBtn').click();
      assert.equal(await page.locator('#hubPage').isVisible(),true);
      await page.locator('#hubCampaignBtn').click();
      assert.equal(await page.locator('#campaignPage').isVisible(),true);
      assert.equal(await page.locator('[data-mission]').count(),3);
      assert.equal(await page.locator('[data-mission="whisperGrove"]').isDisabled(),true);
      await page.screenshot({path:path.join(output,`campaign-${width}.png`),fullPage:true});
      await page.locator('#settingsBtn').click();
      await page.locator('#settingSound').evaluate(node=>{ if(node.checked) node.click(); });
      await page.locator('[data-action="close"]').evaluate(node=>node.click());
      await page.locator('[data-mission="groveGate"]').click();
      await page.locator('[data-support="charge"]').click({force:true});
      await page.locator('[data-difficulty="story"]').click({force:true});
      await page.screenshot({path:path.join(output,`briefing-${width}.png`),fullPage:true});
      await page.locator('[data-action="deploy"]').evaluate(node=>node.click());
      await page.locator('[data-action="scout"]').click();
      assert.equal(await page.evaluate(()=>paused),true);
      const scoutCount=()=>page.locator('.scout-table tbody tr').evaluateAll(rows=>rows.reduce((sum,row)=>sum+Number(row.cells[1].textContent),0));
      assert.equal(await scoutCount(),await page.evaluate(()=>gameSession.currentWave.enemyCount));
      await page.locator('#scoutWave').selectOption('3');
      assert.equal(await scoutCount(),await page.evaluate(()=>gameSession.level.waves[2].enemyCount));
      await page.screenshot({path:path.join(output,`scout-${width}.png`),fullPage:true});
      await page.locator('[data-action="close"]').evaluate(node=>node.click());
      assert.equal(await page.evaluate(()=>paused),false);
      await page.evaluate(()=>window.scrollTo(0,0));
      assert.equal(await page.evaluate(()=>surgeCharge),100);
      assert.equal(await page.evaluate(()=>window.campaignModifiers.hp),.7);
      assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,`Horizontal overflow at ${width}`);
      const canvasStats=await page.evaluate(()=>{
        const data=document.querySelector('canvas').getContext('2d').getImageData(0,0,960,540).data;
        const colors=new Set();for(let i=0;i<data.length;i+=400)colors.add(`${data[i]},${data[i+1]},${data[i+2]}`);
        return colors.size;
      });
      assert.ok(canvasStats>20,'The game canvas must contain rendered scenery');
      assert.equal(await page.evaluate(()=>[...document.images].every(img=>img.complete&&img.naturalWidth>0)),true,'Missing game asset');
      await page.locator('#zoomInBtn').click();await page.locator('#zoomInBtn').click();
      assert.equal(await page.evaluate(()=>window.BattleCamera.zoom()),2);
      await page.locator('#panMapBtn').click();
      const view=await page.locator('.map-viewport').boundingBox();
      const leftBefore=await page.locator('.map-viewport').evaluate(node=>node.scrollLeft);
      await page.mouse.move(view.x+view.width*.6,view.y+view.height*.4);await page.mouse.down();
      await page.mouse.move(view.x+view.width*.6-50,view.y+view.height*.4,{steps:4});await page.mouse.up();
      assert.ok(await page.locator('.map-viewport').evaluate(node=>node.scrollLeft)>leftBefore,'Pan must move the viewport');
      assert.equal(await page.evaluate(()=>towers.length),1,'Panning must not deploy or move guardians');
      await page.locator('#fitMapBtn').click();
      await page.locator('#zoomInBtn').click();await page.locator('#zoomInBtn').click();
      await page.locator('[data-map-seed="4"]').click();
      const board=await page.locator('#game').boundingBox();
      const point=[board.x+board.width*9.5/16,board.y+board.height*3.5/9];
      if(width<=768)await page.touchscreen.tap(...point);else await page.mouse.click(...point);
      assert.equal(await page.evaluate(()=>towers.length),2);
      await page.screenshot({path:path.join(output,`zoom-${width}.png`),fullPage:true});
      await page.locator('#fitMapBtn').click();
      await page.locator('[data-priority="strong"]').click();
      assert.equal(await page.evaluate(()=>selectedTower.targetPriority),'strong');
      await page.locator('#waveBtn').click();
      const first=await page.evaluate(()=>{for(let i=0;i<30;i++)update(.05);return enemies[0].dist;});
      const second=await page.evaluate(()=>{for(let i=0;i<30;i++)update(.05);return enemies[0].dist;});
      assert.ok(second>first,'Enemies must move along the route');
      await page.screenshot({path:path.join(output,`battle-${width}.png`),fullPage:true});
      await page.locator('#battleSettings').click();
      assert.equal(await page.evaluate(()=>paused),true);
      const modalState=await page.evaluate(()=>({charge:surgeCharge,hp:enemies.map(enemy=>enemy.hp)}));
      await page.keyboard.press('p');await page.keyboard.press('Space');
      assert.equal(await page.evaluate(()=>paused),true,'Modal keyboard input must not resume battle');
      assert.deepEqual(await page.evaluate(()=>({charge:surgeCharge,hp:enemies.map(enemy=>enemy.hp)})),modalState,'Modal keyboard input must not release the combat ability');
      await page.locator('#settingSound').evaluate(node=>{ if(node.checked) node.click(); });
      await page.locator('[data-action="close"]').click();
      assert.equal(await page.evaluate(()=>paused),false);
      // End-state fixtures verify UI/storage contracts; combat viability is audited separately.
      await page.evaluate(()=>{enemies=[];spawned=waveSize();kills=waveSize();completeWave();});
      assert.equal(await page.locator('[data-reward]').count(),3);
      const upcomingEvent=await page.evaluate(()=>contentRegistry.events.get(gameSession.currentWave.eventKey).name);
      assert.ok((await page.locator('#storyBody .mission-actions').textContent()).includes(upcomingEvent),'Scouting must describe the next wave event');
      await page.locator('[data-reward="repair"]').click();
      assert.equal(await page.locator('[data-decision]').count(),2);
      assert.equal(await page.evaluate(()=>{startWave();return running;}),false,'A pending story decision must block the next wave');
      await page.screenshot({path:path.join(output,`decision-${width}.png`),fullPage:true});
      await page.locator('[data-decision="north"]').click();
      assert.deepEqual(await page.evaluate(()=>routeWeightsForWave()),[3,1]);
      assert.equal(await page.locator('#storyModal').isHidden(),true);
      let checkpoint=await page.evaluate(()=>window.CampaignSave.peek());
      assert.ok(checkpoint,'The complete preparation must be saved');
      assert.equal(checkpoint.missionDecisions['reward:2'],'repair');
      assert.equal(checkpoint.missionDecisions.gate_signal,'north');
      await page.locator('#waveBtn').click();
      checkpoint=await page.evaluate(()=>window.CampaignSave.peek());
      await page.reload();await page.evaluate(()=>document.fonts.ready);
      await page.locator('#hubCampaignBtn').click();
      await page.locator('#continueCampaignBtn').click();
      assert.equal(await page.evaluate(()=>wave),2);
      assert.equal(await page.evaluate(()=>running),false);
      assert.equal(await page.locator('#storyModal').isHidden(),true,'Claimed rewards and decisions must not replay after reload');
      assert.deepEqual(await page.evaluate(()=>window.CampaignSave.peek()),checkpoint,'Battle must resume from the saved wave preparation');
      assert.deepEqual(await page.evaluate(()=>towers.map(tower=>({...tower.snapshot(),cool:0}))),checkpoint.towers.map(tower=>({...tower,cool:0})));
      assert.equal(await page.evaluate(()=>coins),checkpoint.coins);
      assert.deepEqual(await page.evaluate(()=>missionStory.snapshot()),{gate_signal:'north'});
      await page.evaluate(()=>{while(!gameWon){gameSession.startWave();running=true;enemies=[];spawned=waveSize();completeWave();}});
      await page.screenshot({path:path.join(output,`result-${width}.png`),fullPage:true});
      assert.equal(await page.locator('[data-next="whisperGrove"]').count(),1);
      assert.equal(await page.evaluate(()=>window.CampaignSave.peek()),null,'Victory must clear the active checkpoint');
      assert.equal(await page.locator('.decision-record').count(),1);
      await page.locator('[data-next="whisperGrove"]').click();
      assert.ok((await page.locator('#storyTitle').textContent()).includes('低语古树'));
      await page.reload();await page.evaluate(()=>document.fonts.ready);
      await page.locator('#hubCampaignBtn').click();
      assert.equal(await page.locator('[data-mission="whisperGrove"]').isDisabled(),false);
      assert.equal(await page.evaluate(()=>runtime.soundEnabled),false,'Sound preference must survive reload');
      await page.locator('#chronicleBtn').click();
      assert.ok((await page.locator('.chronicle-entry').textContent()).includes('点亮北侧引路灯'));
      await page.locator('#storyClose').click();
      await page.locator('[data-mission="whisperGrove"]').click();
      await page.locator('[data-action="deploy"]').click();
      await page.evaluate(()=>{pendingEvolution=towers[0];pendingEvolution.level=5;pendingEvolutionStage='primary';openEvolution('primary');});
      for(const key of ['metal','wood','water','fire','earth'])assert.equal(await page.locator(`[data-route="${key}"]`).count(),1);
      await page.screenshot({path:path.join(output,`evolution-${width}.png`),fullPage:true});
      await page.locator('[data-route="wood"]').click();
      assert.equal(await page.locator('#evoModal').getAttribute('aria-hidden'),'true');
      assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);
      console.log(`${width}x${height}: assets, zoom/pan, precise deployment, scouting, evolution choices, movement, modal input, story choice, wave checkpoint, rewards, chronicle and progression passed.`);
      await page.close();
    }
  } finally { await browser.close(); }
})().catch(error=>{console.error(error);process.exitCode=1;});
